# https://hub.docker.com/r/cm2network/csgo/
version: "3"
services:
  csgo-server:
    image: cm2network/csgo:latest
    container_name: csgo-server
    restart: unless-stopped
    ports:
      - ${SRCDS_PORT}:${SRCDS_PORT}/udp
      - ${SRCDS_PORT}:${SRCDS_PORT}
    volumes:
      - "./csgo-data/:/home/steam/csgo-dedicated/"
    env_file:
      - csgo-server.env
