# https://hub.docker.com/r/cm2network/csgo/
version: "3"
services:
  csgo-server:
    image: cm2network/csgo:latest
    container_name: csgo-server
    restart: unless-stopped
    ports:
      - ${SRCDS_PORT}:${SRCDS_PORT}/udp
      - ${SRCDS_PORT}:${SRCDS_PORT}
    volumes:
      - "./csgo-data/:/home/steam/csgo-dedicated/"
    env_file:
      - variables.env
  csgo-rcon:
    image: itzg/rcon
    container_name: csgo-rcon
    ports:
      - "8000:4326"
      - "4327:4327"
    volumes:
      - "./rcon-data/:/opt/rcon-web-admin/db"
    env_file:
      - variables.env
    depends_on:
      - csgo-server
    restart: unless-stopped
